apiVersion: v1
kind: Service
metadata:
  name: todolist
spec:
  ports:
  - port: 8080
  type: ClusterIP
  selector:
    app: todolist
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist
spec:
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
      - name: todolist
        image: todolist:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: todolist
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todolist
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
