apiVersion: v1
kind: Service
metadata:
  name: todolist
spec:
  ports:
  - port: 8080
  type: ClusterIP
  selector:
    app: todolist
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist
spec:
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
      - name: todolist
        image: todolist:latest
        ports:
        - containerPort: 8080
